print ("Enter a value" )
a = int (input())
print ("Enter b value" )
b = int (input())
print ("value of a is",a)
print ("value of b is",b)
print ("value of a+b value is", a+b)
print ("value of a-b value is", a-b)
print ("value of a*b value is", a*b)
print ("value of a/b value is", a/b)