x={1,2,3,3,4}
y={1,2}
print(x|y)
print(x&y)
y.add(3)
print(y)
y.add(3)
print(y)
z={3,4,1,5,2}
print(z)
z.update([6])
print(z)
h={'d','e','f','a','k','l','m'}
print(sorted(h))
l={(1,2),5,6}
print(l)
print(type(l))
x={'Bangalore','Chennai','Delhi'}
print(x)
s=set(['Chennai','Bangalore','Delhi'])
print(s)
print(type(s))
x={1,2,3,4}
y={1,2}
print(x-y)
z=x.copy(y)
print(z)

x={'a','b','c','d','e'}
y={'b','c'}
z={'c','d'}